{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.preference",
    "module": "preference-ktx",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "preference-ktx-1.2.0.aar",
          "url": "preference-ktx-1.2.0.aar",
          "size": 6284,
          "sha512": "c8e6d0135a2ea8fdf02a23f24222b1b28a786546535b5e1e1bc97d0fe03ad98cc35781da2e894aef5d08b85dfe6b48ceb285ae600806e61f0a604076a0284720",
          "sha256": "4c7116888722053aabafb29f020604b02826990c61387d37c0e23509ef17fa83",
          "sha1": "bb1739cebc7daee66311fda77eb458d2575fd5f2",
          "md5": "f8b2714efaacd585314490b8345fcc7c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          },
          "reason": "Mirror preference dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "preference-ktx-1.2.0.aar",
          "url": "preference-ktx-1.2.0.aar",
          "size": 6284,
          "sha512": "c8e6d0135a2ea8fdf02a23f24222b1b28a786546535b5e1e1bc97d0fe03ad98cc35781da2e894aef5d08b85dfe6b48ceb285ae600806e61f0a604076a0284720",
          "sha256": "4c7116888722053aabafb29f020604b02826990c61387d37c0e23509ef17fa83",
          "sha1": "bb1739cebc7daee66311fda77eb458d2575fd5f2",
          "md5": "f8b2714efaacd585314490b8345fcc7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preference-ktx-1.2.0-sources.jar",
          "url": "preference-ktx-1.2.0-sources.jar",
          "size": 1780,
          "sha512": "e4792219a6e1352775bcf39ff8f55beb8d89527e4711be5e63c5525b0d23649280b9c978b15fc8c8ddca7f34e05dae69a668a84458a520ffc35a3074caaf1ad1",
          "sha256": "225d80f9fb06bbd4137a448cdbd094147c9893848e5dbbd959498c2b2b2de700",
          "sha1": "c8df4bdd1cf69b87cbab7120ee314c2c2f6c1bd3",
          "md5": "f2240f2789492e6fc74eed7513ddd436"
        }
      ]
    }
  ]
}
